[package]
name = "imgbb"
version = "0.1.0"
edition = "2021"
authors = ["phusitsom"]
readme = "README.md"
license = "GNU GPLv3"
keywords = ["imgbb", "image", "hosting", "api"]
repository = "https://github.com/phusitsom/imgbb-rs"

[dependencies]
base64 = "0.21.2"
reqwest = { version = "0.11.18", features = ["json", "multipart"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
tokio = { version = "1.29.0", features = ["fs", "macros", "rt-multi-thread"] }
